# Generated by Django 4.1.4 on 2022-12-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("category", models.CharField(max_length=20)),
                ("edition", models.IntegerField()),
            ],
        ),
    ]
